### PR TITLE
chore: package deploy prep ^_~

### PR DESCRIPTION
**Pull request by adebayoileri**

### CODE REVIEW

**Review by Mohamilr — APPROVED** [review]
When do you want to publish it?

**Comment by adebayoileri** [comment]
> When do you want to publish it?

This weekend

**Comment by Mohamilr** [comment]
> > When do you want to publish it?
> 
> This weekend

Why are you not merging the pull request?

**Comment by adebayoileri** [comment]
> > > When do you want to publish it?
> > 
> > 
> > This weekend
> 
> Why are you not merging the pull request?

Till I make all changes ready for deploy

**Pull request merged**
